### ISSUE TITLE
decorators and padded-blocks

### ISSUE THREAD

**Issue by fanatid** [babel/babel-eslint#189]
packages:
```
npm ls --depth=0
...
├── babel-eslint@4.1.3
├── eslint@1.5.1
├── eslint-config-standard@4.4.0
├── eslint-plugin-standard@1.3.1
...
```

code:
```js
let a = function () {}

let b = function () {
  @a
  class X {
    constructor () {}
  }

  return new X()
}

b()
```

error:
```
3:21  error  Block must not be padded by blank lines  padded-blocks
```

**Comment by hzoo** [comment]
This would also be a https://github.com/babel/eslint-plugin-babel rule so add the issue to that repo (since we would need to rewrite the rule to account for decorators). I should probably update the readme to be clearer about this. (Basically this repo is to maintain compatibility with eslint and the other repo I linked is to fix any rules related to es6+ features)
