### ISSUE TITLE
flow type annotations with default parameters in arrow functions fail eslint due to Parsing error: Assigning to rvalue

### ISSUE THREAD

**Issue by davidjnelson** [babel/babel-eslint#190]
If I have code like this:

`
let hello = (greeting:string = ' world') : string => {
	console.log('hello' + greeting);
};

hello();
`

I get a babel-eslint error.

I created a repo to help reproduce it:

https://github.com/davidjnelson/flow-issues

For now I'll workaround by not using default parameters, but I'd sure like them :-)  Thanks so much!

**Comment by sebmck** [comment]
What is the error?

**Comment by davidjnelson** [comment]
Ah, wow that was fast!  :-)  Sorry, forgot to paste the error:

Parsing error: Assigning to rvalue

**Comment by davidjnelson** [comment]
If I don't use arrow functions it works fine, ie:

let hello = function (greeting:string = ' world') : string {
	console.log('hello' + greeting);
};

hello();

**Comment by sebmck** [comment]
This isn't a `babel-eslint` issue. It's a bug in the parser. Please report it on the [babel](https://github.com/babel/babel) repo.

**Comment by davidjnelson** [comment]
Ok.  Will do, thanks!

**Comment by davidjnelson** [comment]
Ok, created: https://github.com/babel/babel/issues/2493

Thanks Sebastian!

**Comment by dchambers** [comment]
This link now 404s:

  * https://github.com/babel/babel/issues/2493

I eventually learned that this was because Babel has switched to Phabricator for their issue tracking, where the Phabricator URL for that issue is here:

  * https://phabricator.babeljs.io/T2493

Annoyingly, the Phabricator issue doesn't contain any useful information, like the related commits or the version of Babel where this was integrated ... sheesh!

Yet more searching and I was eventually able to track down the commit where this was fixed:

  * https://github.com/babel/babel/commit/592193321de8533d3e08adcaea91252f1e964b56

However, the long and short of it is that you currently need to be using babel-eslint 5.0 (in Beta only at the time of writing) if you want to pick this fix up. I changed my config from `^4.1.6` to `^5.0.0-beta6` and now everything's working great :smile:.

**Comment by Velan** [comment]
@dchambers Thanks, I was looking at the same issue, you saved me precious time! :)
