### ISSUE TITLE
decorators and block padding

### ISSUE THREAD

**Issue by necolas** [babel/babel-eslint#196]
I get the "Block must not be padded by blank lines" error with the following code:

```js
 test('message', () => {
    @decorator
    class Foo extends React.Component {
```

Removing the decorator makes the error go away.

**Comment by hzoo** [comment]
This will need to be added as a rule in https://github.com/babel/eslint-plugin-babel (since it involves decorators). Thanks

**Comment by necolas** [comment]
thanks, i didn't know about that plugin

**Comment by hzoo** [comment]
Yeah it's relatively new. The problem is that since eslint doesn't support experimental features the only solution is to recreate the rules (although that has it's own issues like syncing with upstream, etc).

If you want to make the same issue there go ahead or I can do it! Actually I just noticed it is there already https://github.com/babel/eslint-plugin-babel/issues/17.
