### ISSUE TITLE
async (t) => { }    - Expected parentheses around arrow function argument.

### ISSUE THREAD

**Issue by azhang** [babel/babel-eslint#252]
I'm getting `Expected parentheses around arrow function argument. ` errors with `async (t) => {}` and `async t => {}`

**Comment by abritinthebay** [comment]
Yup, very annoying quirk.

**Comment by hzoo** [comment]
Yeah like mentioned in the other issue, you should use eslint-plugin-babel babel.

https://github.com/babel/eslint-plugin-babel/blob/master/tests/arrow-parens.js#L52-L53

This project/repo is just a parser so that you don' the error `Unexpected token`. If the rules are wrong most likely it will need a rewrite using https://github.com/babel/eslint-plugin-babel since the rule itself doesn't know about something (like async) and thus assumes certain things

**Comment by abritinthebay** [comment]
So basically I shouldn't use babel-eslint as a parser at all and just switch to that + eslint as the parser?

It appears that you're saying that eslint-plugin-babel is the actually useful tool here.

**Comment by hzoo** [comment]
Uh not exactly - you need a parser that supports the syntax you are using (async) which currently only is this parser (babel-eslint). However the rules you are using (the ones included by default) don't support the syntax either so you need to use eslint-plugin-babel as well

**Comment by abritinthebay** [comment]
Ah I see, thanks for the clarification. It seemed like you were saying to switch off using this (which seemed strange to me!)

Thanks.
