### ISSUE TITLE
"key" property missing on ClassProperty nodes

### ISSUE THREAD

**Issue by zxqfox** [babel/babel-eslint#308]
Heya.

Code
```js
class NotFound {
    prop = 42;
}
```
according to astexplorer produces ClassProperty without `key` property: http://astexplorer.net/#/JKuvCk4gnJ

`babylon` works fine btw.

**Comment by kaicataldo** [comment]
It looks like it is explicitly deleting the key: https://github.com/babel/babel-eslint/blob/master/babylon-to-espree/toAST.js#L205

I'm assuming that's intentional, but I don't understand why...I can help make a PR if we need to change this though :)

**Comment by hzoo** [comment]
Yeah all things are going to be intentional in this case. If I check history, it's https://github.com/babel/babel-eslint/commit/1bc620f665e9ca7bb19be6c5405b3c18e9b97377. It's possible we can remove things as time passes if its es6. But this is experimental so it was probably deleted for the no-undef or no-unused-vars rule.

If you want to add it back in we'll just need to add some tests for those rules and maybe a few others. Not sure the consequences.

**Comment by kaicataldo** [comment]
Is the missing `key` property causing any known issues? If not, doesn't seem like any changes need to be made.

**Comment by hzoo** [comment]
Ok fixed by defining a variable in scope
