### ISSUE TITLE
ecmaFeatures.impliedStrict isn't respected.

### ISSUE THREAD

**Issue by jdalton** [babel/babel-eslint#503]
When sourceType is `"module"` (default) then the use of `"use strict"` directives should be implied by default. However, I noticed that it's not and that using `{ ecmaFeatures: { impliedStrict: true } }` has no effect. I did find that using `strict: 2` did work though.

**Comment by jmm** [comment]
Hey @jdalton :wave:, I've read this several times and I'm not sure I understand the issue, can you help me out with example input and config and description of expected and actual results? (FWIW I'm asking out of personal curiosity because I was just looking at how the `strict` rule and `sourceType` interact and came across this.)

**Comment by jdalton** [comment]
I'm not sure. It's been a while. I'll close this as stale.

**Comment by jmm** [comment]
Ok thanks.
