### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by hzoo** [babel/babel-eslint#574]
Not sure where else this project should be going, have a few issues that are high level that can be done

- Read from `.babelrc` to get info: https://github.com/babel/babel-eslint/issues/573
- Remove deps and use peerDeps given this project is the intersection of eslint/babel and can use the user's dep versions?
- Finish TS Support: https://github.com/babel/babel-eslint/issues/505
- Smoke test on ESLint/this project (related to https://github.com/babel/babel-eslint/issues/62)
- Easier setup/install? maybe rename to `@babel/eslint` or `@eslint/babel` or even just expose this package itself in another scoped package?
- Should this package move under the eslint org? I don't think it matters as long as everyone as access to github/npm
- What do we do with https://github.com/babel/eslint-plugin-babel? I made https://github.com/babel/eslint-plugin-babel/issues/135 to talk about how it can be more easily maintained and inform the implementation of ESLint if a syntax does get to JS

Anything else?

**Comment by yordis** [comment]
Definitely would love to see the package to be renamed to `@babel/eslint` or `@eslint/babel` depending on the Org that maintains the package.

Putting everything under `@eslint` org makes more sense in term of `where the maintains happens` since the code is related to ESLint compatibility with Babel, no other way around.
