### ISSUE TITLE
How can we improve tests?

### ISSUE THREAD

**Issue by kaicataldo** [babel/babel-eslint#739]
How can we structure and write tests in a way that allows us to catch integration issues (changes in Babel or ESLint)?

As discussed [here](https://github.com/babel/babel-eslint/issues/62), this repo used to (attempt to) test against ESLint's core rules.

**Comment by kaicataldo** [comment]
As discussed [here](https://github.com/babel/babel-eslint/pull/736/files#r247175369), maybe we can switch from Mocha to Jest?

**Comment by hzoo** [comment]
I'm ok with whatever, if it helps with maintenance to switch just since we are using it in Babel itself that's cool!

More was thinking about some other ideas:

- Is it possible to import tests from both @babel/parser or eslint and run them as integration tests?
- When we add a new syntax to Babel itself, can we make sure we have a test/code to handle it in babel-eslint as well? And even test against the common rules like `unused-vars`. It's easy to be out of sync (this is a general problem with flow/ts/jsx/any syntax in all of Babel though)
- Can we structure the tests such that it should be simple for a new contributor to make a PR to start the work?
