### ISSUE TITLE
How to check multiple files?

### ISSUE THREAD

**Issue by mraak** [babel/babel-eslint#757]
I'm following a basic tutorial in the readme. I have the following source code:

/src
 -lib.js
 -index.js
-eslintrc.js

eslintrc.js
```
module.exports = {
  parser: "babel-eslint",
  parserOptions: {
    sourceType: "module",
    allowImportExportEverywhere: false,
    ecmaFeatures: {
      globalReturn: false,
    },
    babelOptions: {
      configFile: "path/to/config.js",
    },
  },
  rules: {
    semi: "error"
}
};
```

index.js
```
import {getFoo} from './lib'
var k = 0

if(i == "3"){

}

console.log('My Webpack Babel Setup ' + **getFoo(2))
```

lib.js
```
export function getFoo(num = 1){
  return "foo"+num
}
```

When I ran `./node_modules/.bin/eslint .\src\index.js` I expected the errors would be reported from all the files and marked in which file it was, but it is only reporting from index.js. How do I need to set this up for multi file checking where the imports are recognized which files need checking?

**Comment by kaicataldo** [comment]
Hi - this isn't an issue with babel-eslint. ESLint is only linting `src/index.js` because you're explicitly telling it to only lint that file. If you want to lint all files in the `src/` directory you'll want to run `./node_modules/.bin/eslint src`.

Check out [ESLint's documentation](https://eslint.org/docs/user-guide/command-line-interface) for more details.
